version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: efood_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=efood
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=efoodb
    volumes:
      - pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: efood_redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  pg_data:
  redis_data:
